<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sPHP KANBAN%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Project information here.')) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/newbdez33/php-kanban" target="_blank"><?php echo $this->translate('Fork php-kanban on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('About php-kanban') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Kanban information')) ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('Get Started') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('About Scrum') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Scrum book: %sScrum XP from the trenches%s'), '<a href="http://www.infoq.com/minibooks/scrum-xp-from-the-trenches">', '</a>') ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('About Team') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Contact Skype: newbdez33')) ?></p>
            </div>
        </div>
    </div>
</div>
